services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - graphion_mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: graphion

volumes:
  graphion_mongo:
